name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter packages get -v
      - run: flutter analyze . -v
      - run: flutter test -v
      - run: flutter build linux -v
      - uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: "build/linux/x64/release/bundle/"

  aarch64_job:
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter packages get -v
      - run: flutter analyze . -v
      - run: flutter test -v
      - run: flutter build linux -v
      - uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: "build/linux/arm64/release/bundle/"