name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            base_image: raspios_lite_arm64:latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          commands: |
            test `uname -m` = ${{ matrix.arch }}
            sudo apt update -y
            sudo apt install -y tar ninja-build libgtk-3-dev
            wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz
            tar xf flutter_linux_3.19.0-stable.tar.xz
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter precache