name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            base_image: raspios_lite_arm64:latest
    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          commands: |
            test `uname -m` = ${{ matrix.arch }}
            sudo apt update -y
            sudo apt autoremove --purge snapd
            sudo apt install -y snapd
            sudo snap install flutter --classic
            sudo apt update -y
            sudo apt install -y ninja-build libgtk-3-dev
            flutter sdk-path